[package]
name = "aoc19"
version = "0.1.0"
authors = ["alex wennerberg <awennerberg@cloudbakers.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = {path="../intcode"}
